//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.ServiceAssist.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailResponseSettings
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public bool ShowJob { get; set; }
        public bool SendReply { get; set; }
        public bool AddAttachment { get; set; }
        public bool AddLink { get; set; }
        public bool CCResponse { get; set; }
        public string Addresses { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
