//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.ServiceAssist.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTPConversionSettings
    {
        public int Id { get; set; }
        public bool AddProcessed { get; set; }
        public bool ReturnResults { get; set; }
        public bool MirrorInput { get; set; }
        public bool MoveProcessed { get; set; }
        public int UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
