//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.ServiceAssist.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTPSettings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FTPSettings()
        {
            this.FTPSettings1 = new HashSet<FTPSettings>();
            this.FTPSettingsTasksUnion = new HashSet<FTPSettingsTasksUnion>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Host { get; set; }
        public Nullable<int> Port { get; set; }
        public string Password { get; set; }
        public string Path { get; set; }
        public bool UseSSL { get; set; }
        public Nullable<bool> DeleteFile { get; set; }
        public int FtpServiceType { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool Enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FTPSettings> FTPSettings1 { get; set; }
        public virtual FTPSettings FTPSettings2 { get; set; }
        public virtual FTPSettingsTypes FTPSettingsTypes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FTPSettingsTasksUnion> FTPSettingsTasksUnion { get; set; }
    }
}
