//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.ServiceAssist.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTPSettings
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Host { get; set; }
        public Nullable<int> Port { get; set; }
        public string Password { get; set; }
        public string Path { get; set; }
        public bool UseSSL { get; set; }
        public bool DeleteFile { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
