//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.ServiceAssist.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserServiceSubscribeStates
    {
        public UserServiceSubscribeStates()
        {
            this.UserServiceSubscribes = new HashSet<UserServiceSubscribes>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UserServiceSubscribes> UserServiceSubscribes { get; set; }
    }
}
