//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.Portal.Api.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FCCPortalEntities : DbContext
    {
        public FCCPortalEntities()
            : base("name=FCCPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<DocumentStates> DocumentStates { get; set; }
        public virtual DbSet<DocumentTypes> DocumentTypes { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<ServiceTypes> ServiceTypes { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TaskStates> TaskStates { get; set; }
        public virtual DbSet<UserLogins> UserLogins { get; set; }
        public virtual DbSet<UserLoginStates> UserLoginStates { get; set; }
        public virtual DbSet<UserRoleTypes> UserRoleTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserServiceSubscribes> UserServiceSubscribes { get; set; }
        public virtual DbSet<UserServiceSubscribeStates> UserServiceSubscribeStates { get; set; }
        public virtual DbSet<UserSettings> UserSettings { get; set; }
    }
}
