//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.Portal.Api.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int Id { get; set; }
        public int SenderId { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public int NotificationTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual NotificationTypes NotificationTypes { get; set; }
        public virtual UserRoleTypes UserRoleTypes { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
