//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.Portal.Api.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionPlans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubscriptionPlans()
        {
            this.SubscriptionPlanUses = new HashSet<SubscriptionPlanUses>();
            this.SubscriptionPlanUses1 = new HashSet<SubscriptionPlanUses>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SubscriptionPlanTypeId { get; set; }
        public Nullable<int> Expiration { get; set; }
        public int CostPerPage { get; set; }
        public int PagesInInterval { get; set; }
        public bool IsDefault { get; set; }
        public int SubscriptionPlanStateId { get; set; }
        public Nullable<int> AltCostPerPage { get; set; }
    
        public virtual SubscriptionPlanStates SubscriptionPlanStates { get; set; }
        public virtual SubscriptionPlanTypes SubscriptionPlanTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionPlanUses> SubscriptionPlanUses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionPlanUses> SubscriptionPlanUses1 { get; set; }
    }
}
