//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.Portal.Api.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public Tasks()
        {
            this.Documents = new HashSet<Documents>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int TaskStateId { get; set; }
        public int UserId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual ServiceTypes ServiceTypes { get; set; }
        public virtual TaskStates TaskStates { get; set; }
        public virtual Users Users { get; set; }
    }
}
