//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.Portal.Api.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfiles()
        {
            this.UserProfileExportFormats = new HashSet<UserProfileExportFormats>();
            this.UserProfileLanguages = new HashSet<UserProfileLanguages>();
            this.UserProfilePrintTypes = new HashSet<UserProfilePrintTypes>();
            this.UserProfileServiceDefault = new HashSet<UserProfileServiceDefault>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public bool Deskew { get; set; }
        public bool RemoveGarbage { get; set; }
        public bool RemoveTexture { get; set; }
        public bool SplitDualPage { get; set; }
        public int RotationTypeId { get; set; }
        public string Resolution { get; set; }
        public string JpegQuality { get; set; }
        public bool SpeedOcr { get; set; }
        public int AnalysisModeId { get; set; }
        public bool LookForBarcodes { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public string Name { get; set; }
        public string OutputFormat { get; set; }
    
        public virtual AnalysisModeCatalog AnalysisModeCatalog { get; set; }
        public virtual RotationTypeCatalog RotationTypeCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfileExportFormats> UserProfileExportFormats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfileLanguages> UserProfileLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfilePrintTypes> UserProfilePrintTypes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfileServiceDefault> UserProfileServiceDefault { get; set; }
    }
}
