//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.EmailAgent.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emails()
        {
            this.EmailContents = new HashSet<EmailContents>();
            this.EmailTransactions = new HashSet<EmailTransactions>();
        }
    
        public int Id { get; set; }
        public string FromEmail { get; set; }
        public int ReceiverUserId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Host { get; set; }
        public Nullable<int> Port { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public int StateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailContents> EmailContents { get; set; }
        public virtual EmailStates EmailStates { get; set; }
        public virtual EmailTypes EmailTypes { get; set; }
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailTransactions> EmailTransactions { get; set; }
    }
}
