//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.EmailAgent.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTransactions
    {
        public int Id { get; set; }
        public int EmailId { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public int State { get; set; }
    
        public virtual Emails Emails { get; set; }
        public virtual EmailTransactionStates EmailTransactionStates { get; set; }
    }
}
