//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.EmailAgent.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FCCEmailAgentEntities : DbContext
    {
        public FCCEmailAgentEntities()
            : base("name=FCCEmailAgentEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmailContents> EmailContents { get; set; }
        public virtual DbSet<Emails> Emails { get; set; }
        public virtual DbSet<EmailStates> EmailStates { get; set; }
        public virtual DbSet<EmailTransactions> EmailTransactions { get; set; }
        public virtual DbSet<EmailTransactionStates> EmailTransactionStates { get; set; }
        public virtual DbSet<EmailTypes> EmailTypes { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Queue> Queue { get; set; }
        public virtual DbSet<QueueStates> QueueStates { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TaskStates> TaskStates { get; set; }
        public virtual DbSet<TaskTypes> TaskTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
