//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexiCapture.Cloud.EmailAgent.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public Tasks()
        {
            this.Emails = new HashSet<Emails>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> ExecutionTime { get; set; }
        public int TaskTypeId { get; set; }
        public Nullable<int> Interval { get; set; }
        public Nullable<int> DayNumber { get; set; }
        public Nullable<int> TaskStateId { get; set; }
    
        public virtual ICollection<Emails> Emails { get; set; }
        public virtual TaskStates TaskStates { get; set; }
        public virtual TaskTypes TaskTypes { get; set; }
    }
}
